#include "lxc-runtime.hpp"


#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>


//const char LXC_PATH[] = "/var/lib/lxc/";
const char LXC_PATH[] = "/cross/container-dev/lxc/";


//-----------------------------------------------------------------------------
// public
//-----------------------------------------------------------------------------
CLXCRuntime::CLXCRuntime()
{
	
	
}
//-----------------------------------------------------------------------------
CLXCRuntime::~CLXCRuntime()
{
	
	
}
//-----------------------------------------------------------------------------
//bool CLXCRuntime::SetConfig(CContainerConfig *pconfig)
//{
//	this->m_pContainerConfig = pconfig;
//}
//-----------------------------------------------------------------------------
bool CLXCRuntime::GetGuestList(std::vector< std::string > &guestlist)
{
	return this->m_ContainerConfig.GetGuestList(guestlist);
}
//-----------------------------------------------------------------------------
bool CLXCRuntime::ExecGuestContainer(std::string guest)
{
	if (this->CreateGuestConfig(guest) == false)
	{
		return false;
	}
	
}
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
// protected
//-----------------------------------------------------------------------------
bool CLXCRuntime::CreateGuestConfig(std::string guest)
{
	bool result = false;
	CConfigElement *pelem = NULL;
	
	if (this->m_ContainerConfig.GetElementByName(guest, &pelem) == true)
	{
		std::string outfile;
		
		outfile = std::string(LXC_PATH) + guest;
		
		::mkdir(outfile.c_str(), (S_IRWXU|S_IRGRP|S_IXGRP|S_IROTH|S_IXOTH));
		
		outfile = outfile + std::string("/config");
		std::ofstream cnfout(outfile, std::ios::trunc);
		
		if (cnfout.is_open())
		{
			Json::Value jsonvalue;
			pelem->GetJsonValue(jsonvalue);
			
			this->HeaderOut(cnfout);
			this->BasicConfigOut(cnfout, jsonvalue);
			this->MountConfigOut(cnfout, jsonvalue);
			this->NetworkConfigOut(cnfout, jsonvalue);
			this->ICCConfigOut(cnfout, jsonvalue);
			
			result = true;
		}
	}
	
	return result;
}
//-----------------------------------------------------------------------------
void CLXCRuntime::HeaderOut(std::ofstream &ofs)
{
	ofs << std::string("# LXC config generated by AGL Container Manager") << std::endl;
}
//-----------------------------------------------------------------------------
void CLXCRuntime::BasicConfigOut(std::ofstream &ofs, Json::Value &json)
{
	std::string containername = json["name"].asString();	//must value
	
	ofs << std::endl;
	ofs << "# basic settings" << std::endl;
	ofs << "lxc.uts.name = \"" << containername  << "\"" << std::endl;
	
	if (json["setting"].isObject() == true )
	{
		//have a child value
		Json::Value setting = json["setting"];
		
		if ( setting.isMember("rootfs") == true )
		{
			Json::Value rootfs = setting["rootfs"];
			if (rootfs["path"].asString().length() > 0)
			{
				ofs << "lxc.rootfs.path = dir:" << rootfs["path"].asString() << std::endl;
			}
		}
		
		if ( setting.isMember("lifecycle") == true)
		{
			Json::Value lifecycle = setting["lifecycle"];
			
			if ( lifecycle.isMember("halt") == true )
			{
				if (lifecycle["halt"].asString().length() > 0)
				{
					ofs << "lxc.signal.halt = " << lifecycle["halt"].asString() << std::endl;
				}
			}
			
			if ( lifecycle.isMember("reboot") == true )
			{
				if (lifecycle["reboot"].asString().length() > 0)
				{
					ofs << "lxc.signal.reboot = " << lifecycle["reboot"].asString() << std::endl;
				}
			}
		}
		
		if ( setting.isMember("cap") == true)
		{
			Json::Value cap = setting["cap"];
			
			if ( cap.isMember("drop") == true )
			{
				if (cap["drop"].asString().length() > 0)
				{
					ofs << "lxc.cap.drop = " << cap["drop"].asString() << std::endl;
				}
			}
			
			if ( cap.isMember("keep") == true )
			{
				if (cap["keep"].asString().length() > 0)
				{
					ofs << "lxc.cap.keep = " << cap["keep"].asString() << std::endl;
				}
			}
		}
	}
	
	ofs << "lxc.tty.max = 1" << std::endl;
	ofs << "lxc.pty.max = 1" << std::endl;
}
//-----------------------------------------------------------------------------
void CLXCRuntime::MountConfigOut(std::ofstream &ofs, Json::Value &json)
{
	ofs << std::endl;
	ofs << "# mount settings" << std::endl;
	
	if (json["mount"].isArray() == true )
	{
		//have a child value
		Json::Value mounts = json["mount"];
		
		Json::Value::ArrayIndex count, max;
		max = mounts.size();
		
		for(count = 0; count < max; count++)
		{
			Json::Value mnt = mounts[count];
			
			// must need parameta
			if ( mnt.isMember("type") == true )
			{
				std::string mounttype = mnt["type"].asString();
			
				if ( mounttype == std::string("auto"))
				{
					if ( mnt.isMember("param") == true )
					{
						ofs << "# standard kernel file systems" << std::endl;
						ofs << "lxc.mount.auto = " << mnt["param"].asString() << std::endl;
						ofs << std::endl;
					}
					else
					{
						//nop
					}
				}
				else
				{
					if ( mnt.isMember("type") && mnt.isMember("from") && mnt.isMember("to") 
						&& mnt.isMember("fstype") && mnt.isMember("option") )
					{
						ofs << "# " << mnt["type"].asString() << " mount" << std::endl;
						
						ofs << "lxc.mount.entry = " << mnt["from"].asString() << " " << mnt["to"].asString() << " "
							<< mnt["fstype"].asString() << " " << mnt["option"].asString() << std::endl;
						
						if (mnt.isMember("devnode") == true)
						{
							dev_t dev;
							
							if (this->GetDevNum(mnt["devnode"].asString(), dev) == true)
							{
								if (major(dev) > 0)
								{
									ofs << "lxc.cgroup.devices.allow = c " << std::to_string(major(dev)) << ":* rwm" << std::endl;
								}
							}
						}
						ofs << std::endl;
					}
				}
			}
			else
			{
				//nop
			}
		}
	}
}
//-----------------------------------------------------------------------------
void CLXCRuntime::NetworkConfigOut(std::ofstream &ofs, Json::Value &json)
{
	ofs << std::endl;
	ofs << "# network settings" << std::endl;
	
	if (json["network"].isArray() == true )
	{
		//have a child value
		Json::Value network = json["network"];
		
		Json::Value::ArrayIndex count, num, max;
		max = network.size();
		num = 0;
		
		for(count = 0; count < max; count++)
		{
			Json::Value net = network[count];
			
			// must need parameta
			if ( net.isMember("type") == true )
			{
				std::string nettype = net["type"].asString();
			
				if ( nettype == std::string("veth"))
				{
					// must need
					if ( net.isMember("link") == true )
					{
						if (net["link"].asString().length() > 0)
						{
							ofs << "# veth device" << std::endl;
							ofs << "lxc.net." << std::to_string(num) << ".type = veth" << std::endl;
							ofs << "lxc.net." << std::to_string(num) << ".link = " << net["link"].asString() << std::endl;
							
							// any
							if ( net.isMember("flags") == true )
							{
								if (net["flags"].asString().length() > 0)
								{
									ofs << "lxc.net." << std::to_string(num) << ".flags = " << net["flags"].asString() << std::endl;
								}
							}
							
							if ( net.isMember("hwaddr") == true )
							{
								if (net["hwaddr"].asString().length() > 0)
								{
									ofs << "lxc.net." << std::to_string(num) << ".hwaddr = " << net["hwaddr"].asString() << std::endl;
								}
							}
							
							if ( net.isMember("veth") == true )
							{
								Json::Value veth = net["veth"];
								
								if ( veth.isMember("mode") == true )
								{
									if (veth["mode"].asString().length() > 0)
									{
										ofs << "lxc.net." << std::to_string(num) << ".veth.mode = " << veth["mode"].asString() << std::endl;
									}
								}
							}
							
							if ( net.isMember("ipv4") == true )
							{
								Json::Value ipv4 = net["ipv4"];
								
								if ( ipv4.isMember("address") == true )
								{
									if (ipv4["address"].asString().length() > 0)
									{
										ofs << "lxc.net." << std::to_string(num) << ".ipv4.address = " << ipv4["address"].asString() << std::endl;
									}
								}
								if ( ipv4.isMember("gateway") == true )
								{
									if (ipv4["gateway"].asString().length() > 0)
									{
										ofs << "lxc.net." << std::to_string(num) << ".ipv4.gateway = " << ipv4["gateway"].asString() << std::endl;
									}
								}
							}
							
							if ( net.isMember("ipv6") == true )
							{
								Json::Value ipv6 = net["ipv6"];
								
								if ( ipv6.isMember("address") == true )
								{
									if (ipv6["address"].asString().length() > 0)
									{
										ofs << "lxc.net." << std::to_string(num) << ".ipv6.address = " << ipv6["address"].asString() << std::endl;
									}
								}
								if ( ipv6.isMember("gateway") == true )
								{
									if (ipv6["gateway"].asString().length() > 0)
									{
										ofs << "lxc.net." << std::to_string(num) << ".ipv6.gateway = " << ipv6["gateway"].asString() << std::endl;
									}
								}
							}
							ofs << std::endl;
							num = num + 1;
						}
						else
						{
							//nop if (net["link"].asString().length() <= 0)
						}
					}
					else
					{
						//nop if ( net.isMember("link") != true )
					}
				}
				else if ( nettype == std::string("can"))
				{
					std::string canhost,canguest;
					
					//CAN デバイス(vxcan)の名称は内部で生成する
					
					ofs << "# can device" << std::endl;
					ofs << "lxc.net." << std::to_string(num) << ".type = phys" << std::endl;
					ofs << "lxc.net." << std::to_string(num) << ".link = " << net["link"].asString() << std::endl;
							
					// any
					if ( net.isMember("flags") == true )
					{
						if (net["flags"].asString().length() > 0)
						{
							ofs << "lxc.net." << std::to_string(num) << ".flags = " << net["flags"].asString() << std::endl;
						}
					}
					else
					{
						//nop if ( net.isMember("link") != true )
					}
				}
			}
			else
			{
				//nop
			}
		}
	}
}
//-----------------------------------------------------------------------------
void CLXCRuntime::ICCConfigOut(std::ofstream &ofs, Json::Value &json)
{
	
}
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
bool CLXCRuntime::GetDevNum(std::string node, dev_t &dev)
{
	struct stat sb = {0};
	
	if (::stat(node.c_str(), &sb) < 0)
	{
		return false;
	}
	
	dev = sb.st_rdev;
	
	return true;
}
//-----------------------------------------------------------------------------
bool CreateCANDevName(std::string &host, std::string &guest)
{
	//とりあえず
	
	host = std::string("vxcan-host0");
	guest = std::string("vxcan-guest0");
	
	return 0;
}
